server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/product/**

  zipkin:
    base-url: http://localhost:9411
    enabled: true

  sleuth:
    sampler:
      probability: 1.0 # traces 100% of requests (for testing)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true


