server:
  port: 8085
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173" # Specifically allow your frontend origin
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=product/api/**
        - id: order
          uri: lb://ORDER
          predicates:
            - Path=order/api/**

  zipkin:
    base-url: http://localhost:9411
    enabled: true

  sleuth:
    sampler:
      probability: 1.0 # traces 100% of requests (for testing)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/{your-realm-name}
          # jwk-set-uri: http://localhost:8080/realms/{your-realm-name}/protocol/openid-connect/certs # Alternatively, you can specify the JWK set URI directly
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true


