server:
  port: 8083
spring:
  datasource:
    jdbc: h2:mem:orderDb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    User Name: sa
    password:
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop  # or create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  application:
    name: ORDER
    admin:
      client:
        url: http://localhost:8081  # URL of the admin server
        instance:
          service-base-url: http://localhost:8080  # 👈 important fix
  cloud:
    discovery:
      enabled: true  # Enable service discovery (Eureka)
  config:
    import: "optional:configserver:"

  zipkin:
    base-url: http://localhost:9411
    enabled: true

  sleuth:
    sampler:
      probability: 1.0 # traces 100% of requests (for testing)
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Or specific ones like "health", "info"
endpoint:
  health:
    show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


