###
GET localhost:8085/order/api/order/api/orders
Content-Type: application/json

<> 2025-04-19T144958.404.json

###
GET  localhost:8085/order/api/api/orders/3
Content-Type: application/json

{
  "name": "",
  "price": 0,
  "status": "",
  "user_": "",
  "product": ""
}

<> 2025-04-19T144959.404.json

###
POST localhost:8085/order/api/api/orders
Content-Type: application/json

<> 2025-04-19T144959-1.404.json