server:
  port: 8081  # Or anything you like

spring:
  application:
    name: spring_admin
    admin:
      client:
        url: http://localhost:8081  # URL of the admin server

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Or specific ones like "health", "info"
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

#  zipkin:
#    base-url: http://localhost:9411
#    enabled: true
#
#  sleuth:
#    sampler:
#      probability: 1.0 # traces 100% of requests (for testing)